package:
  name: python-example
  version: "{{ PACKAGE_VERSION }}"

source:
  path: ../python

requirements:
  build:
    - setuptools

  run:
    - functions-python-api >={{ FUNCTIONS_PYTHON_API_VERSION }}, <1

build:
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt
